apiVersion: v1
kind: Service
metadata:
  name: web-svc
  # Name of the service
spec:
  type: LoadBalancer
  # Specifies that the service is of type LoadBalancer
  selector:
    app: web-app
    # Selects pods with the label 'app: web-app' to direct traffic to
  ports:
    - protocol: TCP
      # Specifies the TCP protocol
      port: 80
      # Specifies the port that external clients will use to access the service
      targetPort: 5000
      # Specifies the port that the service will forward traffic to
      # This is the port that the pods are listening on
